name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: {}
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 3
      - name: Generate Summary
        id: summary
        run: |
          total=$(npx playwright show-report --json | jq '.stats.total')
          passed=$(npx playwright show-report --json | jq '.stats.passed')
          failed=$(npx playwright show-report --json | jq '.stats.failed')
          skipped=$(npx playwright show-report --json | jq '.stats.skipped')
          echo "### Playwright Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Total Tests**: $total" >> $GITHUB_STEP_SUMMARY
          echo "- **Passed**: $passed" >> $GITHUB_STEP_SUMMARY
          echo "- **Failed**: $failed" >> $GITHUB_STEP_SUMMARY
          echo "- **Skipped**: $skipped" >> $GITHUB_STEP_SUMMARY
          echo "- **HTML Report**: [Download here](./artifacts/playwright-html-report)" >> $GITHUB_STEP_SUMMARY
