name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: {}
jobs:
  eslint:
    name: ESLint Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: ESLint Execution
        run: npm run lint

      - name: Formatter Execution
        run: npm run format:check
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
      - name: Run Playwright tests
        run: npm run test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 3

      - name: Generate Summary
        run: |
          if [ -d "playwright-report" ]; then
            echo "### Playwright Test Summary" >> $GITHUB_STEP_SUMMARY
            echo " **HTML Report**: Download the Artifacts to see Playwright Report" >> $GITHUB_STEP_SUMMARY
          else
            echo "No report generated. Please check test execution."
          fi
